version: '3.3'

services:
  db:
    image: mysql:latest
    volumes:
      - /mnt/web/docker-wordpress/mysql:/var/lib/mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordPress123

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    volumes:
      - /mnt/web/docker-wordpress/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordPress123
  
  nginx:
    depends_on:
      - wordpress
    image: richarvey/nginx-php-fpm
    ports:
      - 80:80
    restart: always
    environment:
      POST_MAX_SIZE: 128m
    volumes:
      - /mnt/web/docker-wordpress/nginx:/etc/nginx/sites-enabled
      - /mnt/web/docker-wordpress/wordpress:/var/www/html
       
  admin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - 3000:80
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword123
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordPress123

